flowchart TD
  n_0(["ocr识别"])
  n_1("扫描版PDF")
  n_2("电子版DPF")
  n_3("Process 4")
  n_4("目的是什么")
  n_5("能识别H1-H6 这样的标题")
  n_6("正文表格能识别")
  n_7("图片能识别")
  n_8("docx模板")
  n_9("再识别")
  n_10("docx成果")
  n_0 --> n_0
  n_0 --> n_1
  n_0 --> n_2
