flowchart TD
  n_0("审查MD文件<br/>（和原来SKILL的审查文件一样）")
  n_1["局部修改，修改的内容简单<br/>（和原来SKILL的审查MD文件一样）"]
  n_2["范围大的修改<br/>（部分章节替换补写）"]
  n_3["目录结构<br/>H1 对应的问题<br/>H n要替换的章节（替换的章节的章节等级）"]
  n_0 --> n_1
  n_0 --> n_2
  n_2 --> n_3
