mindmap
  设置的AI工作空间
    日期+ 项目名称  文件夹
      01成果--文件夹
        用于我存放最终资料的地方
      02过程文件--文件夹
        用于存放我过程资料的地方
      03资料--文件夹
        项目的一些资料
      AI空间--文件夹
        prompt_md--文件夹
          make-chatu skill，提示词文件夹
        素材image--文件夹
          make-chatu skill，用于放生成的AI图的文件夹
        过程文件及成果--文件夹
          Ai生成的过程文件及成果
        素材分析汇总--文件夹
          make-sucaitiqu，提取的图片和资料阅读理解汇总的文件夹
      其余资料
        其他一些杂七杂八的资料
